package eu.x_road.emta_v6;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2020-02-15T00:35:05.910+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://emta-v6.x-road.eu", name = "webServiceInterface")
@XmlSeeAlso({eu.x_road.xsd.identifiers.ObjectFactory.class, ObjectFactory.class, eu.x_road.xsd.xroad.ObjectFactory.class})
public interface WebServiceInterface {

    /**
     * 
     *             
     */
    @WebMethod
    @RequestWrapper(localName = "xteeFieAndmed", targetNamespace = "http://emta-v6.x-road.eu", className = "eu.x_road.emta_v6.XteeFieAndmed")
    @ResponseWrapper(localName = "xteeFieAndmedResponse", targetNamespace = "http://emta-v6.x-road.eu", className = "eu.x_road.emta_v6.XteeFieAndmedResponse")
    public void xteeFieAndmed(
        @WebParam(name = "keha", targetNamespace = "")
        eu.x_road.emta_v6.PersonalIdentityCode keha,
        @WebParam(mode = WebParam.Mode.INOUT, name = "client", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType> client,
        @WebParam(mode = WebParam.Mode.INOUT, name = "service", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType> service,
        @WebParam(mode = WebParam.Mode.INOUT, name = "id", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> id,
        @WebParam(mode = WebParam.Mode.INOUT, name = "protocolVersion", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> protocolVersion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "userId", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> userId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "issue", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> issue,
        @WebParam(mode = WebParam.Mode.OUT, name = "paring", targetNamespace = "")
        javax.xml.ws.Holder<PersonalIdentityCode> paring,
        @WebParam(mode = WebParam.Mode.OUT, name = "keha2", targetNamespace = "")
        javax.xml.ws.Holder<XteeFieAndmedResponseType> keha2
    );
}
